GET http://simpleware.ddns.net:1880/nome 
###
GET http://simpleware.ddns.net:1880/usuario 
###
GET http://simpleware.ddns.net:1880/curriculo 
###
GET http://simpleware.ddns.net:1880/escolaridade 
###
GET http://simpleware.ddns.net:1880/desafio